export const API_REQUEST = 'API_REQUEST'
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS'
export const API_REQUEST_FAILURE = 'API_REQUEST_FAILURE'

export const NOTIFICATION_RESET = 'NOTIFICATION_RESET'
export const NOTIFICATION_SET = 'NOTIFICATION_SET'

export const DIALOG_CLOSE = 'DIALOG_CLOSE'
export const DIALOG_OPEN = 'DIALOG_OPEN'

export const PROGRESS_START = 'PROGRESS_START'
export const PROGRESS_STOP = 'PROGRESS_STOP'

export const USER_AUTH = 'USER_AUTH'

export const USER_UPDATE = 'USER_UPDATE'
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'

export const USER_FETCH = 'USER_FETCH'
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'

export const ENTITIES_UPDATE = 'ENTITIES_UPDATE'
export const ENTITIES_UPDATE_REQUEST = 'ENTITIES_UPDATE_REQUEST'
export const ENTITIES_UPDATE_SUCCESS = 'ENTITIES_UPDATE_SUCCESS'
export const ENTITIES_UPDATE_FAILURE = 'ENTITIES_UPDATE_FAILURE'

export const ENTITY_FETCH = 'ENTITY_FETCH'
export const ENTITY_FETCH_REQUEST = 'ENTITY_FETCH_REQUEST'
export const ENTITY_FETCH_SUCCESS = 'ENTITY_FETCH_SUCCESS'
export const ENTITY_FETCH_FAILURE = 'ENTITY_FETCH_FAILURE'

export const ENTITY_CREATE = 'ENTITY_CREATE'
export const ENTITY_CREATE_REQUEST = 'ENTITY_CREATE_REQUEST'
export const ENTITY_CREATE_SUCCESS = 'ENTITY_CREATE_SUCCESS'
export const ENTITY_CREATE_FAILURE = 'ENTITY_CREATE_FAILURE'

export const ENTITY_DELETE = 'ENTITY_DELETE'
export const ENTITY_DELETE_REQUEST = 'ENTITY_DELETE_REQUEST'
export const ENTITY_DELETE_SUCCESS = 'ENTITY_DELETE_SUCCESS'
export const ENTITY_DELETE_FAILURE = 'ENTITY_DELETE_FAILURE'

export const ENTITY_UPDATE = 'ENTITY_UPDATE'
export const ENTITY_UPDATE_REQUEST = 'ENTITY_UPDATE_REQUEST'
export const ENTITY_UPDATE_SUCCESS = 'ENTITY_UPDATE_SUCCESS'
export const ENTITY_UPDATE_FAILURE = 'ENTITY_UPDATE_FAILURE'

export const ENTITIES_FETCH = 'ENTITIES_FETCH'
export const ENTITIES_FETCH_REQUEST = 'ENTITIES_FETCH_REQUEST'
export const ENTITIES_FETCH_SUCCESS = 'ENTITIES_FETCH_SUCCESS'
export const ENTITIES_FETCH_FAILURE = 'ENTITIES_FETCH_FAILURE'

export const ENTITIES_DELETE = 'ENTITIES_DELETE'
export const ENTITIES_DELETE_REQUEST = 'ENTITIES_DELETE_REQUEST'
export const ENTITIES_DELETE_SUCCESS = 'ENTITIES_DELETE_SUCCESS'
export const ENTITIES_DELETE_FAILURE = 'ENTITIES_DELETE_FAILURE'

export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR'
